---
# vars file for deploy_nginx
port_nginx: 81
destin_folder: /etc/nginx/sites-enabled/
destin_index: /var/www/html
menus:
 - name: Home
   link: /home
 - name: Products
   link: /products
 - name: About Us
   link: /about-us
 - name: Contact Us
   link: /contact-us
